sigp/milhouse

- Cargo.toml
- src/tests/proptest/mod.rs
- src/tree.rs
Remove all `patches` and `git` dependencies in favour of `sigp` crates from `crates.io`!
> Use released SigP crates!

- src/diff.rs
- src/list.rs
- src/tests/proptest/operations.rs
- src/vector.rs
This PR implements "rebasing", the act of re-rooting a List or Vect's tree so that it's based on another. This operation is useful if two related trees are created independently (e.g. due to a cache miss/load from disk), as it allows them to share more nodes and use less total memory.
> Implement rebasing

- .github/workflows/release.yml
- .github/workflows/test-suite.yml
- .gitignore
- src/cow.rs
- src/list.rs
- src/tests/packed.rs
- src/vector.rs
This PR adds CI jobs for:
- `cargo fmt` 
- `cargo clippy`
- `cargo test`
- `cargo publish`
> Add CI workflow

- Cargo.toml
Fix the CI failure by removing `pprof` which wasn't being used anyway
Closes #15
> Remove unused dev-deps and fix Windows CI

- src/tests/proptest/operations.rs
- src/vector.rs
Closes #20
The new tests fail if the line that copies the updates is removed, i.e.
```rust
list.interface.updates = vector.interface.updates;
```
> Fix List from Vector conversion

- src/cow.rs
- src/error.rs
- src/interface.rs
- src/tests/proptest/operations.rs
- src/update_map.rs
It is useful to be able to upgrade a `Cow` pointer into its mutable variant without consuming it, which is what `Cow::to_mut` does. This PR adds a new method `Cow::make_mut` which makes the Cow pointer mutable, and returns it. The returned reference has a shorter lifetime than the one returned by `to_mut` because it borrows from `&mut self` rather than `self`.
The `to_mut` method has been renamed `into_mut` as we needed to change its type signature anyway to introduce a `Result` type. The new `make_mut` also returns a `Result`.
> Add `Cow::make_mut`

- Cargo.toml
- benches/rebase.rs
- src/error.rs
- src/list.rs
- src/tests/proptest/mod.rs
- src/tests/proptest/operations.rs
- src/tests/proptest/rebase.rs
- src/tree.rs
- src/vector.rs
This PR implements a specialised `rebase_on` rather than using diffs to rebase. It is between 5-45x faster than the diff approach according to benchmarks.
It tries harder _not_ to recurse unnecessarily, by checking subtree equality using the hash _and_ the length. The length is required because packed leaves of different lengths can have the same hash due to 0 padding (e.g. we can't differentiate between 3x `0u64` and 4x `0xu64`).
It's also faster because it avoids intermediate allocations for the diff (a bunch of btree nodes).
> Fast rebase

- Cargo.toml
- benches/tree_hash_root.rs
Add a benchmark for `tree_hash_root` for both `List` and `Vector`.
> Add benchmarks for `tree_hash_root`

- Cargo.toml
- benches/ssz.rs
- benches/tree_hash_root.rs
Add a new benchmark which tests the SSZ encoding and decoding performance of `List` and `Vector` and compares it to `ssz_types::VariableList`.
There are benchmarks for just encoding and then more benchmarks for encoding + decoding. This was done to separate out the two distinct tasks although there might be a neater way to do this.
> Add new benchmark for SSZ encoding and decoding

- benches/tree_hash_root.rs
Add a benchmark which tree hashes two lists in parallel. This will will allow us to see improvements/regressions relating especially to `RwLock` performance.
> Add parallel tree hashing benchmark

- Cargo.toml
- benches/pop_front.rs
- benches/rebase.rs
- benches/ssz.rs
- src/builder.rs
- src/error.rs
- src/interface.rs
- src/level_iter.rs
- src/lib.rs
- src/list.rs
- src/tests/mod.rs
- src/tests/pop_front.rs
- src/tests/proptest/mod.rs
- src/tests/proptest/operations.rs
- src/tree.rs
- src/utils.rs
- src/vector.rs
For MaxEB we need methods to _slice_ an SSZ list, removing `n` elements from the front.
If `n` has multiple trailing zeros in binary format then we can reuse substantial portions of the tree when slicing, e.g. if `n = 4` we can cheapy clone the subtrees for indices `4`, `8`, `12`, `16` and so on, reordering them under new parent nodes.
This PR tries to implement this algorithm efficiently, by introducing the concept of a "level iterator" which iterates the `Arc`ed internal nodes at a given depth. It combines this with extensions to the tree `Builder` type which enable it to consume these internal nodes and build a tree.
There are new `proptest` tests added to extensively test the functionality, along with unit tests and benchmarks. Benchmarks show that `pop_front` is substantially faster …
> Implement `pop_front` in terms of a level iterator

- src/update_map.rs
The FIXME is no longer relevant as the feature described has been implemented as `MaxMap` and is enabled by default
> Remove outdated FIXME about MaxMap

- .github/workflows/test-suite.yml
Windows is misbehaving: https://github.com/sigp/milhouse/actions/runs/11770903510/job/32788485925?pr=52
> Skip fuzzing targets on windows

- Cargo.toml
- src/leaf.rs
- src/list.rs
- src/packed_leaf.rs
- src/tree.rs
- src/vector.rs
Derivative is unmaintained (see https://rustsec.org/advisories/RUSTSEC-2024-0388), so I think we should switch to `educe` across all of our crates.
> Switch from derivative to educe

- src/builder.rs
- src/cow.rs
- src/interface_iter.rs
- src/iter.rs
A handful of uncontroversial lints ☺️
> Fix clippy lints for Rust 1.83

- Cargo.toml
This coincides with a new release of the SSZ crates: https://github.com/sigp/ethereum_ssz/releases/tag/v0.8.1
> Bump SSZ version to `0.8.1`

- Cargo.toml
Bumps versions for some `sigp` crates.
Related to this effort: https://github.com/sigp/lighthouse/pull/6609
> Bump versions of various `sigp` crates

- src/list.rs
- src/vector.rs
We had only partly abstracted over the type `U` used for storing pending updates to lists/vectors. This PR updates several of the trait implementations so that they work with any choice of `U`, not just the default `VecMap`.
It may be advantageous to use a different map type now that the validator set has grown. The size of a `VecMap` is `O(largest index)`, so I suspect we are allocating _a lot_ of very large vecs on networks with millions of validators (mainnet, Holesky). A `BTreeMap` may be more efficient in terms of speed and memory usage at this point. I will do some benchmarks with Lighthouse against this branch before merging.
> Abstract over `U: UpdateMap` more

- Cargo.toml
- src/tests/mod.rs
- src/tests/serde.rs
Inspired by @pawanjay176's PR to `ssz_types`, these tests ensure that `milhouse`'s `Deserialize` implementations maintain length invariants. They do!
See also:
- https://github.com/sigp/ssz_types/pull/43
> Test serde deserialization

- src/error.rs
- src/list.rs
- src/tests/proptest/operations.rs
- src/tree.rs
- src/vector.rs
While debugging high memory usage on Holesky, we found that the changing `inactivity_scores` were occupying a large amount of RAM: around 70MB of new data each epoch boundary. See:
- https://github.com/sigp/lighthouse/issues/7053#issuecomment-2693115614
With this change, we can reduce it down to 4MB, with a rebase op taking only 42ms.
The `intra_rebase` implementation is a recursive depth-first tree traversal. It's similar to `rebase`, but a bit simpler.
> Implement `intra_rebase` to reuse identical subtrees

- src/list.rs
- src/tests/proptest/operations.rs
- src/vector.rs
Remove pre-conditions from `intra_rebase` about applying updates and tree hashing. We can just do these inline because we have a mutable reference.
This fixes a bug found by @eserilev in my first impl of intra_rebase in LH, which forgot to tree hash before calling the method :man_facepalming:
> Make intra_rebase more user friendly

- src/builder.rs
- src/error.rs
- src/interface.rs
- src/interface_iter.rs
- src/list.rs
- src/repeat.rs
- src/serde.rs
- src/vector.rs
Fix some Clippy lints, mostly just error formatting.
> Fix Clippy lints for Rust 1.88

- Cargo.toml
- fuzz/Cargo.toml
- src/interface.rs
- src/leaf.rs
- src/lib.rs
- src/list.rs
- src/packed_leaf.rs
- src/tree.rs
- src/update_map.rs
- src/utils.rs
- src/vector.rs
This is part of an effort to feature gate the `arbitrary` crate from lighthouse's `types` crate. Will open a PR in the Lighthouse repo tomorrow with these changes: https://github.com/risc0-labs/lighthouse/tree/ec2/arbitrary-unstable
> Put arbitrary crate behind a feature
